# -*- coding: utf-8 -*-
"""spain_wc26_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O02eoWvaRmTvtwjFw0AVIGfSzA9ybOlW
"""

import pandas as pd
import matplotlib.pyplot as plt

matches = pd.read_csv("spain_wc2026_matches.csv")
players = pd.read_csv("spain_wc2026_player_advanced_stats.csv")
scorers = pd.read_csv("spain_wc2026_scorers_final.csv")
xg_teams = pd.read_csv("spain_wc2026_team_xg_efficiency.csv")

print(matches.head())
print(players.head())
print(scorers.head())
print(xg_teams.head())

matches["goal_diff"] = matches["goals_for"] - matches["goals_against"]
matches["cumulative_gf"] = matches["goals_for"].cumsum()
matches["cumulative_ga"] = matches["goals_against"].cumsum()
matches["clean_sheet"] = matches["goals_against"] == 0

fig, axes = plt.subplots(2, 2, figsize=(13, 9))

axes[0, 0].bar(matches["opponent"], matches["goals_for"], color="#14213D", label="Goals scored")
axes[0, 0].bar(matches["opponent"], -matches["goals_against"], color="#C9A227", label="Goals conceeded")
axes[0, 0].set_title("Goals scored vs conceeded per game")
axes[0, 0].axhline(0, color="black", linewidth=0.8)
axes[0, 0].tick_params(axis="x", rotation=45)
axes[0, 0].legend()

axes[0, 1].plot(matches["opponent"], matches["cumulative_gf"], marker="o", color="#14213D", label="sum scored goals")
axes[0, 1].plot(matches["opponent"], matches["cumulative_ga"], marker="o", color="#C9A227", label="sum conceeded goals")
axes[0, 1].set_title("Cumulated evolution of the goals across the tournament")
axes[0, 1].tick_params(axis="x", rotation=45)
axes[0, 1].legend()

scorers_players = scorers[scorers["player"] != "Own goal (opponent)"].sort_values("goals", ascending=True)
axes[1, 0].barh(scorers_players["player"], scorers_players["goals"], color="#14213D")
axes[1, 0].set_title("WC26 Spain goalscorers")
axes[1, 0].set_xlabel("Goals")

passers = players.dropna(subset=["openplay_passes_completed"]).sort_values("openplay_passes_completed", ascending=True)
axes[1, 1].barh(passers["player"], passers["openplay_passes_completed"], color="#C9A227")
axes[1, 1].set_title("Volume Open play succeded passes (Key players)")
axes[1, 1].set_xlabel("Succeded pass")

plt.tight_layout()
plt.savefig("spain_wc2026_dashboard.png", dpi=150)
plt.show()

colors_goals = ["#C9A227" if team == "Spain" else "#14213D" for team in xg_teams["team"]]

fig2, ax2 = plt.subplots(figsize=(10, 6))
x = range(len(xg_teams))
width = 0.35

ax2.bar([i - width/2 for i in x], xg_teams["goals"], width, color=colors_goals, label="Goals scored")
ax2.bar([i + width/2 for i in x], xg_teams["xg"], width, color="#8C8C8C", label="xG (Waited for)")

ax2.set_xticks(list(x))
ax2.set_xticklabels(xg_teams["team"], rotation=45)
ax2.set_title("Goals scored vs xG - Top 6 teams of the tournament")
ax2.set_ylabel("Goals")
ax2.legend()

plt.tight_layout()
plt.savefig("spain_wc2026_xg_comparison.png", dpi=150)
plt.show()

golden = pd.read_csv("spain_wc2026_golden_boot_top5.csv")

stars = golden[golden["team"] != "Spain"][["player", "goals"]]
spain_scorers = scorers[scorers["player"] != "Own goal (opponent)"][["player", "goals"]]

combined = pd.concat([stars, spain_scorers]).sort_values("goals", ascending=True)

colors_combined = ["#14213D" if p in spain_scorers["player"].values else "#8C8C8C" for p in combined["player"]]

fig3, ax3 = plt.subplots(figsize=(10, 7))
ax3.barh(combined["player"], combined["goals"], color=colors_combined)
ax3.set_title("Individual Stars vs Spain's Collective Scoring")
ax3.set_xlabel("Goals")

plt.tight_layout()
plt.savefig("spain_wc2026_scorers_collective.png", dpi=150)
plt.show()

ppda = pd.read_csv("spain_wc2026_pressing_ppda.csv")

colors_ppda = ["#C9A227" if team == "Spain" else "#14213D" for team in ppda["team"]]

fig4, ax4 = plt.subplots(figsize=(8, 5))
bars = ax4.bar(ppda["team"], ppda["ppda"], color=colors_ppda)

for bar in bars:
    height = bar.get_height()
    ax4.annotate(f"{height}", xy=(bar.get_x() + bar.get_width() / 2, height),
                 xytext=(0, 3), textcoords="offset points", ha="center")

ax4.set_title("PPDA - Top 3 Pressing Teams (lower = more intense press)")
ax4.set_ylabel("PPDA")

plt.tight_layout()
plt.savefig("spain_wc2026_ppda_top3.png", dpi=150)
plt.show()

from google.colab import files

files.download("spain_wc2026_dashboard.png")
files.download("spain_wc2026_xg_comparison.png")
files.download("spain_wc2026_scorers_collective.png")
files.download("spain_wc2026_ppda_top3.png")

git add spain_wc2026_dashboard.png spain_wc2026_xg_comparison.png spain_wc2026_scorers_collective.png spain_wc2026_ppda_top3.png spain_wc2026_analysis_v2.py
git commit -m "Add Spain WC2026 analysis: dashboard, xG, scorers, pressing"
git push
